use async_trait::async_trait;
use anyhow::Result;
use sea_orm::{DatabaseConnection, EntityTrait, QueryFilter, ColumnTrait, Set};
use std::sync::Arc;
use crate::db::{tasks, task_notes, work_logs};
use crate::storage::Storage;

pub struct DatabaseStorage {
    db: Arc<DatabaseConnection>,
}

impl DatabaseStorage {
    pub fn new(db: Arc<DatabaseConnection>) -> Self {
        Self { db }
    }
}

#[async_trait]
impl Storage for DatabaseStorage {
    async fn load_tasks(&self) -> Result<Vec<tasks::Model>> {
        let tasks = tasks::Entity::find()
            .all(self.db.as_ref())
            .await?;
        Ok(tasks)
    }
    
    async fn save_tasks(&self, tasks_list: &[tasks::Model]) -> Result<()> {
        use sea_orm::sea_query::OnConflict;
        
        for task in tasks_list {
            let active_model = tasks::ActiveModel {
                asana_id: Set(task.asana_id.clone()),
                title: Set(task.title.clone()),
                description: Set(task.description.clone()),
                status: Set(task.status.clone()),
                priority: Set(task.priority.clone()),
                due_date: Set(task.due_date),
                github_pr_url: Set(task.github_pr_url.clone()),
                review_status: Set(task.review_status.clone()),
                last_updated_at: Set(task.last_updated_at),
                ..Default::default()
            };
            
            // Use upsert on asana_id (unique key) to handle conflicts
            // id is auto-generated by database, so we don't set it
            tasks::Entity::insert(active_model)
                .on_conflict(
                    OnConflict::column(tasks::Column::AsanaId)
                        .update_columns([
                            tasks::Column::Title,
                            tasks::Column::Description,
                            tasks::Column::Status,
                            tasks::Column::Priority,
                            tasks::Column::DueDate,
                            tasks::Column::GithubPrUrl,
                            tasks::Column::ReviewStatus,
                            tasks::Column::LastUpdatedAt,
                        ])
                        .to_owned()
                )
                .exec(self.db.as_ref())
                .await?;
        }
        Ok(())
    }
    
    async fn load_notes(&self, task_id: i32) -> Result<Vec<task_notes::Model>> {
        let notes = task_notes::Entity::find()
            .filter(task_notes::Column::TaskId.eq(task_id))
            .all(self.db.as_ref())
            .await?;
        Ok(notes)
    }
    
    async fn load_all_notes(&self) -> Result<Vec<task_notes::Model>> {
        let notes = task_notes::Entity::find()
            .all(self.db.as_ref())
            .await?;
        Ok(notes)
    }
    
    async fn save_note(&self, note: &task_notes::Model) -> Result<task_notes::Model> {
        let active_model = task_notes::ActiveModel {
            task_id: Set(note.task_id),
            content: Set(note.content.clone()),
            ..Default::default()
        };
        
        let saved = task_notes::Entity::insert(active_model)
            .exec_with_returning(self.db.as_ref())
            .await?;
        
        Ok(saved)
    }
    
    async fn load_all_work_logs(&self) -> Result<Vec<work_logs::Model>> {
        let logs = work_logs::Entity::find()
            .all(self.db.as_ref())
            .await?;
        Ok(logs)
    }
    
    async fn save_work_log(&self, log: &work_logs::Model) -> Result<()> {
        let active_model = work_logs::ActiveModel {
            task_id: Set(log.task_id),
            start_time: Set(log.start_time),
            end_time: Set(log.end_time),
            duration_seconds: Set(log.duration_seconds),
            created_at: Set(chrono::Utc::now().naive_utc()),
            ..Default::default()
        };
        
        work_logs::Entity::insert(active_model)
            .exec(self.db.as_ref())
            .await?;
        
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sea_orm::{DbBackend, MockDatabase};
    use chrono::Utc;

    #[tokio::test]
    async fn test_database_storage_load_tasks() {
        let db = MockDatabase::new(DbBackend::Postgres)
            .append_query_results([
                vec![tasks::Model {
                    id: 1,
                    asana_id: "test123".to_string(),
                    title: "Test Task".to_string(),
                    description: None,
                    status: "In Progress".to_string(),
                    priority: None,
                    due_date: None,
                    github_pr_url: None,
                    review_status: None,
                    last_updated_at: Utc::now().naive_utc(),
                }],
            ])
            .into_connection();

        let storage = DatabaseStorage::new(Arc::new(db));
        let tasks = storage.load_tasks().await.unwrap();
        
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].title, "Test Task");
    }

    #[tokio::test]
    async fn test_database_storage_load_notes() {
        let db = MockDatabase::new(DbBackend::Postgres)
            .append_query_results([
                vec![task_notes::Model {
                    id: 1,
                    task_id: 1,
                    content: "Test note".to_string(),
                    created_at: Utc::now().naive_utc(),
                }],
            ])
            .into_connection();

        let storage = DatabaseStorage::new(Arc::new(db));
        let notes = storage.load_notes(1).await.unwrap();
        
        assert_eq!(notes.len(), 1);
        assert_eq!(notes[0].content, "Test note");
    }

    #[tokio::test]
    async fn test_database_storage_save_note() {
        let db = MockDatabase::new(DbBackend::Postgres)
            .append_query_results([
                vec![task_notes::Model {
                    id: 1,
                    task_id: 1,
                    content: "New note".to_string(),
                    created_at: Utc::now().naive_utc(),
                }],
            ])
            .into_connection();

        let storage = DatabaseStorage::new(Arc::new(db));
        let note = task_notes::Model {
            id: 0,
            task_id: 1,
            content: "New note".to_string(),
            created_at: Utc::now().naive_utc(),
        };
        
        let saved = storage.save_note(&note).await.unwrap();
        assert_eq!(saved.id, 1);
        assert_eq!(saved.content, "New note");
    }
}
